# Generated by Django 3.0.3 on 2022-02-12 06:43

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_text_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Address Text Table',
            },
        ),
        migrations.CreateModel(
            name='bennar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/product_image')),
            ],
            options={
                'verbose_name_plural': 'Bennar',
            },
        ),
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Blog_video', models.FileField(blank=True, default=None, null=True, upload_to='Blog_video')),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 33, 321830))),
            ],
            options={
                'verbose_name_plural': 'Blog Post',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=255)),
                ('Brand_discription', models.TextField(default='')),
                ('Brand_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/category_img')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('catalog_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_discription', models.TextField()),
                ('Category_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/category_img')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='contact_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Table',
            },
        ),
        migrations.CreateModel(
            name='Custom_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Company_Name', models.CharField(max_length=255)),
                ('Email_Adress', models.CharField(max_length=255)),
                ('Phone_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Project_Name', models.CharField(max_length=255)),
                ('Details', models.TextField(blank=True, null=True)),
                ('Attach_File', models.FileField(blank=True, null=True, upload_to='custom_project/attach/')),
            ],
            options={
                'verbose_name_plural': 'Custom Project',
            },
        ),
        migrations.CreateModel(
            name='Discount_Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('discount_percentage', models.IntegerField(default='0')),
                ('active_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Discount Coupon',
            },
        ),
        migrations.CreateModel(
            name='job_post_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Job Post Status',
            },
        ),
        migrations.CreateModel(
            name='Navbar_logo_text_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Navbar Logo Text Table',
            },
        ),
        migrations.CreateModel(
            name='newsletter_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 33, 325821))),
            ],
            options={
                'verbose_name_plural': 'Newsletter Table',
            },
        ),
        migrations.CreateModel(
            name='Number_Table_Navbar_Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Number Table Navbar Footer',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategory', models.CharField(max_length=255)),
                ('Subcategory_discription', models.TextField()),
                ('Subcategory_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/Subcategory_img')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.Categories')),
            ],
            options={
                'verbose_name_plural': 'Subcategory',
            },
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('product_status', models.CharField(choices=[('New', 'New'), ('In stock', 'In stock'), ('Out stock', 'Out stock')], default='New', max_length=255)),
                ('catalogue', models.FileField(blank=True, default='', null=True, upload_to='uploads/catalogue')),
                ('datasheets', models.FileField(blank=True, default='', null=True, upload_to='uploads/datasheets')),
                ('Brands', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.Brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.Categories')),
                ('subcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.Subcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Table',
            },
        ),
        migrations.CreateModel(
            name='posted_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('job_details', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('job_location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('post_date', models.DateField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 33, 316842))),
                ('email', models.CharField(blank=True, max_length=255)),
                ('job_post_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.job_post_status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posted Jobs',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('items_json', models.TextField()),
                ('full_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('full_address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('order_date', models.DateField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 33, 317840))),
                ('Discount_Coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.Discount_Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'All Orders',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Email-Confirmed',
            },
        ),
        migrations.CreateModel(
            name='Blogs_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_subject', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 33, 323825))),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.blog_post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs Comments',
            },
        ),
    ]
